/*******************************************************************************
 * Copyright (c) 2013 EclipseSource.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    EclipseSource - initial API and implementation
 ******************************************************************************/
package com.eclipsesource.rap.punchy.eclipsecon;


public class KFZ {

  public final static String[][] DE = new String[][]{
    new String[]{ "A", "Stadt Augsburg", "Augsburg", "Bayern" },
    new String[]{ "AA", "Ostalbkreis in Aalen", "Aalen", "Baden-Württemberg" },
    new String[]{ "AB", "Landkreis Aschaffenburg (XX 999)", "Aschaffenburg", "Bayern" },
    new String[]{ "ABG", "Landkreis Altenburger Land in Altenburg", "Altenburg", "Thüringen" },
    new String[]{ "ABI", "Landkreis Anhalt-Bitterfeld in Köthen (Anhalt)", "Anhalt-Bitterfeld", "Sachsen-Anhalt" },
    new String[]{ "AC", "Städteregion Aachen", "Aachen", "Nordrhein-Westfalen" },
    new String[]{ "AE", "Vogtlandkreis", "Auerbach/Vogtl.", "Sachsen" },
    new String[]{ "AH", "Kreis Borken", "Ahaus", "Nordrhein-Westfalen" },
    new String[]{ "AIC", "Landkreis Aichach-Friedberg in Aichach", "Aichach", "Bayern" },
    new String[]{ "AK", "Landkreis Altenkirchen (Westerwald)", "Altenkirchen", "Rheinland-Pfalz" },
    new String[]{ "ALF", "Landkreis Hildesheim", "Alfeld (Leine)", "Niedersachsen" },
    new String[]{ "AM", "Stadt Amberg", "Amberg", "Bayern" },
    new String[]{ "AN", "Landkreis Ansbach (XX 999)", "Ansbach", "Bayern" },
    new String[]{ "ANA", "Erzgebirgskreis", "Annaberg-Buchholz", "Sachsen" },
    new String[]{ "ANK", "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "Anklam", "Mecklenburg-Vorpommern" },
    new String[]{ "AÖ", "Landkreis Altötting", "Altötting", "Bayern" },
    new String[]{ "AP", "Landkreis Weimarer Land in Apolda", "Apolda", "Thüringen" },
    new String[]{ "APD", "Landkreis Weimarer Land", "Apolda", "Thüringen" },
    new String[]{ "ARN", "Ilm-Kreis", "Arnstadt", "Thüringen" },
    new String[]{ "ART", "Kyffhäuserkreis", "Artern", "Thüringen" },
    new String[]{ "AS", "Landkreis Amberg-Sulzbach in Amberg", "Amberg-Sulzbach", "Bayern" },
    new String[]{ "ASL", "Salzlandkreis", "Aschersleben", "Sachsen-Anhalt" },
    new String[]{ "ASZ", "Erzgebirgskreis", "Landkreis Aue-Schwarzenberg", "Sachsen" },
    new String[]{ "AT", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Altentreptow", "Mecklenburg-Vorpommern" },
    new String[]{ "AU", "Erzgebirgskreis", "Aue (Sachsen)", "Sachsen" },
    new String[]{ "AUR", "Landkreis Aurich", "Aurich", "Niedersachsen" },
    new String[]{ "AW", "Landkreis Ahrweiler in Bad Neuenahr-Ahrweiler", "Ahrweiler", "Rheinland-Pfalz" },
    new String[]{ "AZ", "Landkreis Alzey-Worms in Alzey", "Alzey", "Rheinland-Pfalz" },
    new String[]{ "AZE", "Landkreis Anhalt-Bitterfeld", "Anhalt-Zerbst", "Sachsen-Anhalt" },
    new String[]{ "B", "Stadt Berlin", "Berlin", "Berlin" },
    new String[]{ "BA", "Landkreis Bamberg", "Bamberg", "Bayern" },
    new String[]{ "BAD", "Stadt Baden-Baden", "Baden-Baden", "Baden-Württemberg" },
    new String[]{ "BAR", "Landkreis Barnim in Eberswalde", "Barnim", "Brandenburg" },
    new String[]{ "BB", "Landkreis Böblingen", "Böblingen", "Baden-Württemberg" },
    new String[]{ "BBG", "Salzlandkreis", "Bernburg", "Sachsen-Anhalt" },
    new String[]{ "BBL", "Brandenburg", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Brandenburgische Landesregierung", "Brandenburg" },
    new String[]{ "BC", "Landkreis Biberach", "Biberach", "Baden-Württemberg" },
    new String[]{ "BCH", "Neckar-Odenwald-Kreis", "Buchen (Odenwald)", "Baden-Württemberg" },
    new String[]{ "BD", "Deutscher Bundestag", " Bundesrat", " Bundespräsidialamt", " Bundesregierung", " Bundesministerien", " Bundesfinanzverwaltung und Bundesverfassungsgerichtnew String[]{2}", "Bund", "bundesweit" },
    new String[]{ "BED", "Landkreis Mittelsachsen", "Brand-Erbisdorf", "Sachsen" },
    new String[]{ "BER", "Landkreis Barnim", "Bernau bei Berlin", "Brandenburg" },
    new String[]{ "BGL", "Landkreis Berchtesgadener Land in Bad Reichenhall", "Berchtesgadener Land", "Bayern" },
    new String[]{ "BI", "Stadt Bielefeld", "Bielefeld", "Nordrhein-Westfalen" },
    new String[]{ "BID", "Landkreis Marburg-Biedenkopf", "Biedenkopf", "Hessen" },
    new String[]{ "BIN", "Landkreis Mainz-Bingen", "Bingen", "Rheinland-Pfalz" },
    new String[]{ "BIR", "Landkreis Birkenfeld", "Birkenfeld", "Rheinland-Pfalz" },
    new String[]{ "BIT", "Eifelkreis Bitburg-Prüm in Bitburg", "Bitburg", "Rheinland-Pfalz" },
    new String[]{ "BIW", "Landkreis Bautzen", "Bischofswerda", "Sachsen" },
    new String[]{ "BK", "Landkreis Börde in Haldensleben", "Börde(kreis)", "Sachsen-Anhalt" },
    new String[]{ "BKS", "Landkreis Bernkastel-Wittlich", "Bernkastel-Kues", "Rheinland-Pfalz" },
    new String[]{ "BL", "Zollernalbkreis in Balingen", "Balingen", "Baden-Württemberg" },
    new String[]{ "BLB", "Kreis Siegen-Wittgenstein", "Bad Berleburg", "Nordrhein-Westfalen" },
    new String[]{ "BLK", "Burgenlandkreis in Naumburg (Saale)", "Burgenlandkreis", "Sachsen-Anhalt" },
    new String[]{ "BM", "Rhein-Erft-Kreis in Bergheim", "Bergheim", "Nordrhein-Westfalen" },
    new String[]{ "BN", "Stadt Bonn", "Bonn", "Nordrhein-Westfalen" },
    new String[]{ "BNA", "Landkreis Leipzig", "Borna", "Sachsen" },
    new String[]{ "BO", "Stadt Bochum", "Bochum", "Nordrhein-Westfalen" },
    new String[]{ "BÖ", "Landkreis Börde", "Börde", "Sachsen-Anhalt" },
    new String[]{ "BOH", "Kreis Borken", "Bocholt", "Nordrhein-Westfalen" },
    new String[]{ "BOR", "Kreis Borken", "Borken", "Nordrhein-Westfalen" },
    new String[]{ "BOT", "Stadt Bottrop", "Bottrop", "Nordrhein-Westfalen" },
    new String[]{ "BP", "Bundespolizei", "Bundespolizei", "bundesweit" },
    new String[]{ "BRA", "Landkreis Wesermarsch in Brake (Unterweser)", "Brake", "Niedersachsen" },
    new String[]{ "BRB", "Stadt Brandenburg an der Havel", "Brandenburg", "Brandenburg" },
    new String[]{ "BRG", "Landkreis Jerichower Land", "Burg bei Magdeburg", "Sachsen-Anhalt" },
    new String[]{ "BRL", "Landkreis Goslar", "Braunlage", "Niedersachsen" },
    new String[]{ "BRV", "Landkreis Rotenburg (Wümme)", "Bremervörde", "Niedersachsen" },
    new String[]{ "BS", "Stadt Braunschweig", "Braunschweig", "Niedersachsen" },
    new String[]{ "BT", "Landkreis Bayreuth", "Bayreuth", "Bayern" },
    new String[]{ "BTF", "Landkreis Anhalt-Bitterfeld", "Bitterfeld", "Sachsen-Anhalt" },
    new String[]{ "BÜD", "Wetteraukreis", "Büdingen", "Hessen" },
    new String[]{ "BÜS", "Gemeinde Büsingen am Hochrhein (Gemeinde gehört zum Landkreis Konstanz", " ist aber Enklave in der Schweiz; deshalb eigenes Kennzeichen)", "Büsingen", "Baden-Württemberg" },
    new String[]{ "BÜZ", "Landkreis Rostock", "Bützow", "Mecklenburg-Vorpommern" },
    new String[]{ "BW", "Wasser- und Schifffahrtsverwaltung des Bundes", "Bundes-Wasser- und Schifffahrtsverwaltung", "bundesweit" },
    new String[]{ "BWL", "Baden-Württemberg", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Baden-Württembergischer Landtag", "Baden-Württemberg" },
    new String[]{ "BYL", "Bayern", " Landesregierung und Landtag", "Bayerischer Landtag", "Bayern" },
    new String[]{ "BZ", "Landkreis Bautzen", "Bautzen", "Sachsen" },
    new String[]{ "C", "Stadt Chemnitz", "Chemnitz", "Sachsen" },
    new String[]{ "CA", "Landkreis Oberspreewald-Lausitz", "Calau", "Brandenburg" },
    new String[]{ "CAS", "Kreis Recklinghausen", "Castrop-Rauxel", "Nordrhein-Westfalen" },
    new String[]{ "CB", "Stadt Cottbus", "Cottbus", "Brandenburg" },
    new String[]{ "CE", "Landkreis Celle", "Celle", "Niedersachsen" },
    new String[]{ "CHA", "Landkreis Cham", "Cham", "Bayern" },
    new String[]{ "CLP", "Landkreis Cloppenburg", "Cloppenburg", "Niedersachsen" },
    new String[]{ "CLZ", "Landkreis Goslar", "Clausthal-Zellerfeld", "Niedersachsen" },
    new String[]{ "CO", "Landkreis Coburg (XX 999)", "Coburg", "Bayern" },
    new String[]{ "COC", "Landkreis Cochem-Zell in Cochem", "Cochem", "Rheinland-Pfalz" },
    new String[]{ "COE", "Kreis Coesfeld", "Coesfeld", "Nordrhein-Westfalen" },
    new String[]{ "CUX", "Landkreis Cuxhaven", "Cuxhaven", "Niedersachsen" },
    new String[]{ "CW", "Landkreis Calw", "Calw", "Baden-Württemberg" },
    new String[]{ "D", "Stadt Düsseldorf", "Düsseldorf", "Nordrhein-Westfalen" },
    new String[]{ "DA", "Stadt Darmstadt (XX 999)", "Darmstadt", "Hessen" },
    new String[]{ "DAH", "Landkreis Dachau", "Dachau", "Bayern" },
    new String[]{ "DAN", "Landkreis Lüchow-Dannenberg in Lüchow", "Dannenberg", "Niedersachsen" },
    new String[]{ "DAU", "Landkreis Vulkaneifel in Daun", "Daun", "Rheinland-Pfalz" },
    new String[]{ "DBR", "Landkreis Rostock", "Bad Doberan", "Mecklenburg-Vorpommern" },
    new String[]{ "DD", "Stadt Dresden", "Dresden", "Sachsen" },
    new String[]{ "DE", "Stadt Dessau-Roßlau", "Dessau", "Sachsen-Anhalt" },
    new String[]{ "DEG", "Landkreis Deggendorf", "Deggendorf", "Bayern" },
    new String[]{ "DEL", "Stadt Delmenhorst", "Delmenhorst", "Niedersachsen" },
    new String[]{ "DGF", "Landkreis Dingolfing-Landau in Dingolfing", "Dingolfing", "Bayern" },
    new String[]{ "DH", "Landkreis Diepholz", "Diepholz", "Niedersachsen" },
    new String[]{ "DI", "Landkreis Darmstadt-Dieburg", "Dieburg", "Hessen" },
    new String[]{ "DIN", "Kreis Wesel", "Dinslaken", "Nordrhein-Westfalen" },
    new String[]{ "DL", "Landkreis Mittelsachsen", "Döbeln", "Sachsen" },
    new String[]{ "DLG", "Landkreis Dillingen an der Donau", "Dillingen", "Bayern" },
    new String[]{ "DM", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Demmin", "Mecklenburg-Vorpommern" },
    new String[]{ "DN", "Kreis Düren", "Düren", "Nordrhein-Westfalen" },
    new String[]{ "DO", "Stadt Dortmund", "Dortmund", "Nordrhein-Westfalen" },
    new String[]{ "DON", "Landkreis Donau-Ries in Donauwörth", "Donauwörth", "Bayern" },
    new String[]{ "DU", "Stadt Duisburg", "Duisburg", "Nordrhein-Westfalen" },
    new String[]{ "DUD", "Landkreis Göttingen", "Duderstadt", "Niedersachsen" },
    new String[]{ "DÜW", "Landkreis Bad Dürkheim", "Bad Dürkheim an der Weinstraße", "Rheinland-Pfalz" },
    new String[]{ "DW", "Landkreis Sächsische Schweiz-Osterzgebirge", "Dippoldiswalde", "Sachsen" },
    new String[]{ "DZ", "Landkreis Nordsachsen", "Delitzsch", "Sachsen" },
    new String[]{ "E", "Stadt Essen", "Essen", "Nordrhein-Westfalen" },
    new String[]{ "EA", "Stadt Eisenach", "Eisenach", "Thüringen" },
    new String[]{ "EB", "Landkreis Nordsachsen", "Eilenburg", "Sachsen" },
    new String[]{ "EBE", "Landkreis Ebersberg", "Ebersberg", "Bayern" },
    new String[]{ "ECK", "Kreis Rendsburg-Eckernförde", "Eckernförde", "Schleswig-Holstein" },
    new String[]{ "ED", "Landkreis Erding", "Erding", "Bayern" },
    new String[]{ "EE", "Landkreis Elbe-Elster in Herzberg (Elster)", "Elbe-Elster", "Brandenburg" },
    new String[]{ "EF", "Stadt Erfurt", "Erfurt", "Thüringen" },
    new String[]{ "EI", "Landkreis Eichstätt", "Eichstätt", "Bayern" },
    new String[]{ "EIC", "Landkreis Eichsfeld in Heilbad Heiligenstadt", "Eichsfeld", "Thüringen" },
    new String[]{ "EIL", "Landkreis Mansfeld-Südharz", "Eisleben", "Sachsen-Anhalt" },
    new String[]{ "EIN", "Landkreis Northeim", "Einbeck", "Niedersachsen" },
    new String[]{ "EIS", "Saale-Holzland-Kreis", "Eisenberg", "Thüringen" },
    new String[]{ "EL", "Landkreis Emsland in Meppen", "Emsland", "Niedersachsen" },
    new String[]{ "EM", "Landkreis Emmendingen", "Emmendingen", "Baden-Württemberg" },
    new String[]{ "EMD", "Stadt Emden", "Emden", "Niedersachsen" },
    new String[]{ "EMS", "Rhein-Lahn-Kreis in Bad Ems", "Bad Ems", "Rheinland-Pfalz" },
    new String[]{ "EN", "Ennepe-Ruhr-Kreis in Schwelm", "Ennepe", "Nordrhein-Westfalen" },
    new String[]{ "ER", "Stadt Erlangen", "Erlangen", "Bayern" },
    new String[]{ "ERB", "Odenwaldkreis in Erbach (Odenwald)", "Erbach", "Hessen" },
    new String[]{ "ERH", "Landkreis Erlangen-Höchstadt in Erlangen", "Erlangen-Höchstadt", "Bayern" },
    new String[]{ "ERZ", "Erzgebirgskreis in Annaberg-Buchholz", "Erzgebirge", "Sachsen" },
    new String[]{ "ES", "Landkreis Esslingen", "Esslingen", "Baden-Württemberg" },
    new String[]{ "ESW", "Werra-Meißner-Kreis in Eschwege", "Eschwege", "Hessen" },
    new String[]{ "EU", "Kreis Euskirchen", "Euskirchen", "Nordrhein-Westfalen" },
    new String[]{ "EW", "Landkreis Barnim", "Eberswalde", "Brandenburg" },
    new String[]{ "F", "Stadt Frankfurt am Main", "Frankfurt", "Hessen" },
    new String[]{ "FB", "Wetteraukreis in Friedberg (Hessen)", "Friedberg", "Hessen" },
    new String[]{ "FD", "Landkreis Fulda", "Fulda", "Hessen" },
    new String[]{ "FDS", "Landkreis Freudenstadt", "Freudenstadt", "Baden-Württemberg" },
    new String[]{ "FF", "Stadt Frankfurt (Oder)", "Frankfurt", "Brandenburg" },
    new String[]{ "FFB", "Landkreis Fürstenfeldbruck", "Fürstenfeldbruck", "Bayern" },
    new String[]{ "FG", "Landkreis Mittelsachsen in Freiberg", "Freiberg", "Sachsen" },
    new String[]{ "FL", "Stadt Flensburg", "Flensburg", "Schleswig-Holstein" },
    new String[]{ "FLÖ", "Landkreis Mittelsachsen", "Flöha", "Sachsen" },
    new String[]{ "FN", "Bodenseekreis in Friedrichshafen", "Friedrichshafen", "Baden-Württemberg" },
    new String[]{ "FO", "Landkreis Forchheim", "Forchheim", "Bayern" },
    new String[]{ "FOR", "Landkreis Spree-Neiße", "Forst (Lausitz)", "Brandenburg" },
    new String[]{ "FR", "Stadt Freiburg im Breisgau (XX 999 und NA-ZZ 9999)", "Freiburg", "Baden-Württemberg" },
    new String[]{ "FRG", "Landkreis Freyung-Grafenau in Freyung", "Freyung-Grafenau", "Bayern" },
    new String[]{ "FRI", "Landkreis Friesland in Jever", "Friesland", "Niedersachsen" },
    new String[]{ "FRW", "Landkreis Märkisch-Oderland", "Bad Freienwalde (Oder)", "Brandenburg" },
    new String[]{ "FS", "Landkreis Freising", "Freising", "Bayern" },
    new String[]{ "FT", "Stadt Frankenthal (Pfalz)", "Frankenthal", "Rheinland-Pfalz" },
    new String[]{ "FTL", "Landkreis Sächsische Schweiz-Osterzgebirge", "Freital", "Sachsen" },
    new String[]{ "FÜ", "Stadt Fürth (XX 999)", "Fürth", "Bayern" },
    new String[]{ "G", "Stadt Gera", "Gera", "Thüringen" },
    new String[]{ "GA", "Altmarkkreis Salzwedel", "Gardelegen", "Sachsen-Anhalt" },
    new String[]{ "GAN", "Landkreis Northeim", "Bad Gandersheim", "Niedersachsen" },
    new String[]{ "GAP", "Landkreis Garmisch-Partenkirchen", "Garmisch-Partenkirchen", "Bayern" },
    new String[]{ "GC", "Landkreis Zwickau", "Glauchau", "Sachsen" },
    new String[]{ "GD", "Ostalbkreis", "Schwäbisch Gmünd", "Baden-Württemberg" },
    new String[]{ "GDB", "Landkreis Nordwestmecklenburg", "Gadebusch", "Mecklenburg-Vorpommern" },
    new String[]{ "GE", "Stadt Gelsenkirchen", "Gelsenkirchen", "Nordrhein-Westfalen" },
    new String[]{ "GER", "Landkreis Germersheim", "Germersheim", "Rheinland-Pfalz" },
    new String[]{ "GF", "Landkreis Gifhorn", "Gifhorn", "Niedersachsen" },
    new String[]{ "GG", "Landkreis Groß-Gerau", "Groß-Gerau", "Hessen" },
    new String[]{ "GHA", "Landkreis Leipzig", "Geithain", "Sachsen" },
    new String[]{ "GHC", "Landkreis Wittenberg", "Gräfenhainichen", "Sachsen-Anhalt" },
    new String[]{ "GI", "Landkreis Gießen", "Gießen", "Hessen" },
    new String[]{ "GL", "Rheinisch-Bergischer Kreis in Bergisch Gladbach", "(Bergisch) Gladbach", "Nordrhein-Westfalen" },
    new String[]{ "GLA", "Kreis Recklinghausen", "Gladbeck", "Nordrhein-Westfalen" },
    new String[]{ "GM", "Oberbergischer Kreis in Gummersbach", "Gummersbach", "Nordrhein-Westfalen" },
    new String[]{ "GMN", "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "Grimmen", "Mecklenburg-Vorpommern" },
    new String[]{ "GN", "Main-Kinzig-Kreis (ohne die Stadt Hanau)", "Gelnhausen", "Hessen" },
    new String[]{ "GNT", "Landkreis Jerichower Land", "Genthin", "Sachsen-Anhalt" },
    new String[]{ "GÖ", "Landkreis Göttingen", " Göttingen", "Niedersachsen" },
    new String[]{ "GOA", "Rhein-Hunsrück-Kreis", "St. Goar", "Rheinland-Pfalz" },
    new String[]{ "GP", "Landkreis Göppingen", "Göppingen", "Baden-Württemberg" },
    new String[]{ "GR", "Landkreis Görlitz", "Görlitz", "Sachsen" },
    new String[]{ "GRH", "Landkreis Meißen", "Großenhain", "Sachsen" },
    new String[]{ "GRM", "Landkreis Leipzig", "Grimma", "Sachsen" },
    new String[]{ "GRZ", "Landkreis Greiz", "Greiz", "Thüringen" },
    new String[]{ "GS", "Landkreis Goslar", "Goslar", "Niedersachsen" },
    new String[]{ "GT", "Kreis Gütersloh", "Gütersloh", "Nordrhein-Westfalen" },
    new String[]{ "GTH", "Landkreis Gotha", "Gotha", "Thüringen" },
    new String[]{ "GÜ", "Landkreis Rostock", "Güstrow", "Mecklenburg-Vorpommern" },
    new String[]{ "GUB", "Landkreis Spree-Neiße", "Guben", "Brandenburg" },
    new String[]{ "GVM", "Landkreis Nordwestmecklenburg", "Grevesmühlen", "Mecklenburg-Vorpommern" },
    new String[]{ "GW", "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "Greifswald", "Mecklenburg-Vorpommern" },
    new String[]{ "GZ", "Landkreis Günzburg", "Günzburg", "Bayern" },
    new String[]{ "H", "Region Hannover", " Hannover", "Niedersachsen" },
    new String[]{ "HA", "Stadt Hagen", "Hagen", "Nordrhein-Westfalen" },
    new String[]{ "HAL", "Stadt Halle (Saale)", "Halle", "Sachsen-Anhalt" },
    new String[]{ "HAM", "Stadt Hamm", "Hamm", "Nordrhein-Westfalen" },
    new String[]{ "HAS", "Landkreis Haßberge in Haßfurt", "Haßberge oder Haßfurt", "Bayern" },
    new String[]{ "HB", "Stadt Bremerhaven (X 9999)", "Hansestadt Bremen", "Bremen" },
    new String[]{ "HBN", "Landkreis Hildburghausen", "Hildburghausen", "Thüringen" },
    new String[]{ "HBS", "Landkreis Harz", "Halberstadt", "Sachsen-Anhalt" },
    new String[]{ "HC", "Landkreis Mittelsachsen", "Hainichen", "Sachsen" },
    new String[]{ "HCH", "Zollernalbkreis", "Hechingen", "Baden-Württemberg" },
    new String[]{ "HD", "Rhein-Neckar-Kreis in Heidelberg (XX 999 und 9999)", "Heidelberg", "Baden-Württemberg" },
    new String[]{ "HDH", "Landkreis Heidenheim", "Heidenheim", "Baden-Württemberg" },
    new String[]{ "HDL", "Landkreis Börde", "Haldensleben", "Sachsen-Anhalt" },
    new String[]{ "HE", "Landkreis Helmstedt", "Helmstedt", "Niedersachsen" },
    new String[]{ "HEF", "Landkreis Hersfeld-Rotenburg in Bad Hersfeld", "Bad Hersfeld", "Hessen" },
    new String[]{ "HEI", "Kreis Dithmarschen in Heide (Holstein)", "Heide", "Schleswig-Holstein" },
    new String[]{ "HEL", "Hessen", " Landesregierung und Landtag", "Hessischer Landtag", "Hessen" },
    new String[]{ "HER", "Stadt Herne", "Herne", "Nordrhein-Westfalen" },
    new String[]{ "HET", "Landkreis Mansfeld-Südharz", "Hettstedt", "Sachsen-Anhalt" },
    new String[]{ "HF", "Kreis Herford", "Herford", "Nordrhein-Westfalen" },
    new String[]{ "HG", "Hochtaunuskreis in Bad Homburg vor der Höhe", "Bad Homburg", "Hessen" },
    new String[]{ "HGW", "Stadt Greifswald (Große kreisangehörige Stadt im Landkreis Vorpommern-Greifswald)", "Hansestadt Greifswald", "Mecklenburg-Vorpommern" },
    new String[]{ "HH", "Freie und Hansestadt Hamburg", " Senat und Bürgerschaft", "Hansestadt Hamburg", "Hamburg" },
    new String[]{ "HHM", "Burgenlandkreis", "Hohenmölsen", "Sachsen-Anhalt" },
    new String[]{ "HI", "Landkreis Hildesheim", "Hildesheim", "Niedersachsen" },
    new String[]{ "HIG", "Landkreis Eichsfeld", "Heiligenstadt", "Thüringen" },
    new String[]{ "HK", "Landkreis Heidekreis in Bad Fallingbostel", "Heidekreis", "Niedersachsen" },
    new String[]{ "HL", "Stadt Lübeck", "Hansestadt Lübeck", "Schleswig-Holstein" },
    new String[]{ "HM", "Landkreis Hameln-Pyrmont in Hameln", "Hameln", "Niedersachsen" },
    new String[]{ "HMÜ", "Landkreis Göttingen", "Hann. Münden", "Niedersachsen" },
    new String[]{ "HN", "Landkreis Heilbronn (XX 999 und AA-MZ 9999)", "Heilbronn", "Baden-Württemberg" },
    new String[]{ "HO", "Landkreis Hof (XX 999)", "Hof", "Bayern" },
    new String[]{ "HOG", "Landkreis Kassel", "Hofgeismar", "Hessen" },
    new String[]{ "HOL", "Landkreis Holzminden", "Holzminden", "Niedersachsen" },
    new String[]{ "HOM", "Saarpfalz-Kreis in Homburg (ohne die Stadt St. Ingbert)", "Homburg", "Saarland" },
    new String[]{ "HOT", "Landkreis Zwickau", "Hohenstein-Ernstthal", "Sachsen" },
    new String[]{ "HP", "Kreis Bergstraße in Heppenheim (Bergstraße)", "Heppenheim", "Hessen" },
    new String[]{ "HR", "Schwalm-Eder-Kreis in Homberg (Efze)", "Homberg", "Hessen" },
    new String[]{ "HRO", "Stadt Rostock", "Hansestadt Rostock", "Mecklenburg-Vorpommern" },
    new String[]{ "HS", "Kreis Heinsberg", "Heinsberg", "Nordrhein-Westfalen" },
    new String[]{ "HSK", "Hochsauerlandkreis in Meschede", "Hochsauerlandkreis", "Nordrhein-Westfalen" },
    new String[]{ "HST", "Stadt Stralsund (Große kreisangehörige Stadt im Landkreis Vorpommern-Rügen)", "Hansestadt Stralsund", "Mecklenburg-Vorpommern" },
    new String[]{ "HU", "Stadt Hanau (Sonderstatusstadt im Main-Kinzig-Kreis)", "Hanau", "Hessen" },
    new String[]{ "HV", "Landkreis Stendal", "Havelberg", "Sachsen-Anhalt" },
    new String[]{ "HVL", "Landkreis Havelland in Rathenow", "Havelland", "Brandenburg" },
    new String[]{ "HWI", "Stadt Wismar (Große kreisangehörige Stadt im Landkreis Nordwestmecklenburg)", "Hansestadt Wismar", "Mecklenburg-Vorpommern" },
    new String[]{ "HX", "Kreis Höxter", "Höxter", "Nordrhein-Westfalen" },
    new String[]{ "HY", "Landkreis Bautzen", "Hoyerswerda", "Sachsen" },
    new String[]{ "HZ", "Landkreis Harz in Halberstadt", "Harz", "Sachsen-Anhalt" },
    new String[]{ "IGB", "Stadt St. Ingbert (Mittelstadt im Saarpfalz-Kreis)", "St. Ingbert", "Saarland" },
    new String[]{ "IK", "Ilm-Kreis in Arnstadt", "Ilm-Kreis", "Thüringen" },
    new String[]{ "IL", "Ilm-Kreis", "Ilmenau", "Thüringen" },
    new String[]{ "IN", "Stadt Ingolstadt", "Ingolstadt", "Bayern" },
    new String[]{ "IZ", "Kreis Steinburg in Itzehoe", "Itzehoe", "Schleswig-Holstein" },
    new String[]{ "J", "Stadt Jena", "Jena", "Thüringen" },
    new String[]{ "JE", "Landkreis Wittenberg", "Jessen (Elster)", "Sachsen-Anhalt" },
    new String[]{ "JL", "Landkreis Jerichower Land in Burg", "Jerichower Land", "Sachsen-Anhalt" },
    new String[]{ "JÜL", "Kreis Düren", "Jülich", "Nordrhein-Westfalen" },
    new String[]{ "K", "Stadt Köln", "Köln", "Nordrhein-Westfalen" },
    new String[]{ "KA", "Stadt Karlsruhe (XX 999 und NA-ZZ 9999)", "Karlsruhe", "Baden-Württemberg" },
    new String[]{ "KB", "Landkreis Waldeck-Frankenberg in Korbach", "Korbach", "Hessen" },
    new String[]{ "KC", "Landkreis Kronach", "Kronach", "Bayern" },
    new String[]{ "KE", "Stadt Kempten (Allgäu)", "Kempten", "Bayern" },
    new String[]{ "KEH", "Landkreis Kelheim", "Kelheim", "Bayern" },
    new String[]{ "KF", "Stadt Kaufbeuren", "Kaufbeuren", "Bayern" },
    new String[]{ "KG", "Landkreis Bad Kissingen", "Bad Kissingen", "Bayern" },
    new String[]{ "KH", "Landkreis Bad Kreuznach", "Bad Kreuznach", "Rheinland-Pfalz" },
    new String[]{ "KI", "Stadt Kiel", "Kiel", "Schleswig-Holstein" },
    new String[]{ "KIB", "Donnersbergkreis in Kirchheimbolanden", "Kirchheimbolanden", "Rheinland-Pfalz" },
    new String[]{ "KL", "Landkreis Kaiserslautern (XX 999)", "Kaiserslautern", "Rheinland-Pfalz" },
    new String[]{ "KLE", "Kreis Kleve", "Kleve", "Nordrhein-Westfalen" },
    new String[]{ "KLZ", "Altmarkkreis Salzwedel", "Klötze", "Sachsen-Anhalt" },
    new String[]{ "KM", "Landkreis Bautzen", "Kamenz", "Sachsen" },
    new String[]{ "KN", "Landkreis Konstanz (ohne die Gemeinde Büsingen am Hochrhein)", "Konstanz", "Baden-Württemberg" },
    new String[]{ "KO", "Stadt Koblenz", "Koblenz", "Rheinland-Pfalz" },
    new String[]{ "KÖT", "Landkreis Anhalt-Bitterfeld", "Köthen (Anhalt)", "Sachsen-Anhalt" },
    new String[]{ "KR", "Stadt Krefeld", "Krefeld", "Nordrhein-Westfalen" },
    new String[]{ "KS", "Stadt Kassel (XX 999)", "Kassel", "Hessen" },
    new String[]{ "KT", "Landkreis Kitzingen", "Kitzingen", "Bayern" },
    new String[]{ "KU", "Landkreis Kulmbach", "Kulmbach", "Bayern" },
    new String[]{ "KÜN", "Hohenlohekreis in Künzelsau", "Künzelsau", "Baden-Württemberg" },
    new String[]{ "KUS", "Landkreis Kusel", "Kusel", "Rheinland-Pfalz" },
    new String[]{ "KY", "Landkreis Ostprignitz-Ruppin", "Kyritz", "Brandenburg" },
    new String[]{ "KYF", "Kyffhäuserkreis in Sondershausen", "Kyffhäuser", "Thüringen" },
    new String[]{ "L", "Stadt Leipzig (A–T und AA-TZ)", "Leipzig", "Sachsen" },
    new String[]{ "LA", "Landkreis Landshut (XX 999)", "Landshut", "Bayern" },
    new String[]{ "LAU", "Landkreis Nürnberger Land in Lauf an der Pegnitz", "Lauf", "Bayern" },
    new String[]{ "LB", "Landkreis Ludwigsburg", "Ludwigsburg", "Baden-Württemberg" },
    new String[]{ "LBS", "Saale-Orla-Kreis", "Lobenstein", "Thüringen" },
    new String[]{ "LD", "Stadt Landau in der Pfalz", "Landau", "Rheinland-Pfalz" },
    new String[]{ "LDK", "Lahn-Dill-Kreis in Wetzlar (ohne die Stadt Wetzlar)", "Lahn-Dill-Kreis", "Hessen" },
    new String[]{ "LDS", "Landkreis Dahme-Spreewald in Lübben (Spreewald)", "Landkreis Dahme-Spreewald", "Brandenburg" },
    new String[]{ "LEO", "Landkreis Böblingen", "Leonberg", "Baden-Württemberg" },
    new String[]{ "LER", "Landkreis Leer", "Leer", "Niedersachsen" },
    new String[]{ "LEV", "Stadt Leverkusen", "Leverkusen", "Nordrhein-Westfalen" },
    new String[]{ "LG", "Landkreis Lüneburg", "Lüneburg", "Niedersachsen" },
    new String[]{ "LI", "Landkreis Lindau (Bodensee)", "Lindau", "Bayern" },
    new String[]{ "LIF", "Landkreis Lichtenfels", "Lichtenfels", "Bayern" },
    new String[]{ "LIP", "Kreis Lippe in Detmold", "Lippe", "Nordrhein-Westfalen" },
    new String[]{ "LL", "Landkreis Landsberg am Lech", "Landsberg am Lech", "Bayern" },
    new String[]{ "LM", "Landkreis Limburg-Weilburg in Limburg an der Lahn", "Limburg", "Hessen" },
    new String[]{ "LÖ", "Landkreis Lörrach", "Lörrach", "Baden-Württemberg" },
    new String[]{ "LÖB", "Landkreis Görlitz", "Löbau", "Sachsen" },
    new String[]{ "LOS", "Landkreis Oder-Spree in Beeskow", "Landkreis Oder-Spree", "Brandenburg" },
    new String[]{ "LP", "Kreis Soest", "Lippstadt", "Nordrhein-Westfalen" },
    new String[]{ "LRO", "Landkreis Rostock in Güstrow", "Landkreis Rostock", "Mecklenburg-Vorpommern" },
    new String[]{ "LSA", "Sachsen-Anhalt", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Land Sachsen-Anhalt", "Sachsen-Anhalt" },
    new String[]{ "LSN", "Sachsen", " Landesregierung und Landtag", "Landtag Sachsen", "Sachsen" },
    new String[]{ "LSZ", "Unstrut-Hainich-Kreis", "Bad Langensalza", "Thüringen" },
    new String[]{ "LU", "Stadt Ludwigshafen am Rhein", "Ludwigshafen", "Rheinland-Pfalz" },
    new String[]{ "LÜN", "Kreis Unna", "Lünen", "Nordrhein-Westfalen" },
    new String[]{ "LWL", "Landkreis Ludwigslust (jetzt Landkreis Ludwigslust-Parchim)", "Ludwigslust", "Mecklenburg-Vorpommern" },
    new String[]{ "M", "Stadt München (XX 999 und 9999)", "München", "Bayern" },
    new String[]{ "MA", "Stadt Mannheim", "Mannheim", "Baden-Württemberg" },
    new String[]{ "MAB", "Erzgebirgskreis", "Marienberg", "Sachsen" },
    new String[]{ "MB", "Landkreis Miesbach", "Miesbach", "Bayern" },
    new String[]{ "MC", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Malchin", "Mecklenburg-Vorpommern" },
    new String[]{ "MD", "Stadt Magdeburg", "Magdeburg", "Sachsen-Anhalt" },
    new String[]{ "ME", "Kreis Mettmann", "Mettmann", "Nordrhein-Westfalen" },
    new String[]{ "MEI", "Landkreis Meißen", "Meißen", "Sachsen" },
    new String[]{ "MEK", "Erzgebirgskreis", "Mittlerer Erzgebirgskreis", "Sachsen" },
    new String[]{ "MER", "Saalekreis", "Merseburg", "Sachsen-Anhalt" },
    new String[]{ "MG", "Stadt Mönchengladbach", "Mönchengladbach", "Nordrhein-Westfalen" },
    new String[]{ "MGN", "Landkreis Schmalkalden-Meiningen", "Meiningen", "Thüringen" },
    new String[]{ "MH", "Stadt Mülheim an der Ruhr", "Mülheim an der Ruhr", "Nordrhein-Westfalen" },
    new String[]{ "MHL", "Unstrut-Hainich-Kreis", "Mühlhausen/Thüringen", "Thüringen" },
    new String[]{ "MI", "Kreis Minden-Lübbecke in Minden", "Minden", "Nordrhein-Westfalen" },
    new String[]{ "MIL", "Landkreis Miltenberg", "Miltenberg", "Bayern" },
    new String[]{ "MK", "Märkischer Kreis in Lüdenscheid", "Grafschaft Mark", "Nordrhein-Westfalen" },
    new String[]{ "MKK", "Main-Kinzig-Kreis in Gelnhausen (ohne die Stadt Hanau)", "Main-Kinzig-Kreis", "Hessen" },
    new String[]{ "ML", "Landkreis Mansfeld-Südharz", "Mansfelder Land", "Sachsen-Anhalt" },
    new String[]{ "MM", "Stadt Memmingen", "Memmingen", "Bayern" },
    new String[]{ "MN", "Landkreis Unterallgäu in Mindelheim", "Mindelheim", "Bayern" },
    new String[]{ "MO", "Kreis Wesel", "Moers", "Nordrhein-Westfalen" },
    new String[]{ "MOL", "Landkreis Märkisch-Oderland in Seelow", "Märkisch-Oderland", "Brandenburg" },
    new String[]{ "MOS", "Neckar-Odenwald-Kreis in Mosbach", "Mosbach", "Baden-Württemberg" },
    new String[]{ "MQ", "Saalekreis", "Merseburg-Querfurt", "Sachsen-Anhalt" },
    new String[]{ "MR", "Landkreis Marburg-Biedenkopf in Marburg", "Marburg-Biedenkopf", "Hessen" },
    new String[]{ "MS", "Stadt Münster (Westfalen)", "Münster", "Nordrhein-Westfalen" },
    new String[]{ "MSH", "Landkreis Mansfeld-Südharz in Sangerhausen", "Mansfeld-Südharz", "Sachsen-Anhalt" },
    new String[]{ "MSP", "Landkreis Main-Spessart in Karlstadt", "Main-Spessart", "Bayern" },
    new String[]{ "MST", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Mecklenburg-Strelitz", "Mecklenburg-Vorpommern" },
    new String[]{ "MTK", "Main-Taunus-Kreis in Hofheim am Taunus", "Main-Taunus-Kreis", "Hessen" },
    new String[]{ "MTL", "Landkreis Leipzig", "Muldentalkreis", "Sachsen" },
    new String[]{ "MÜ", "Landkreis Mühldorf am Inn", "Mühldorf", "Bayern" },
    new String[]{ "MÜR", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Müritz", "Mecklenburg-Vorpommern" },
    new String[]{ "MVL", "Mecklenburg-Vorpommern", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Mecklenburg-Vorpommerscher Landtag", "Mecklenburg-Vorpommern" },
    new String[]{ "MW", "Landkreis Mittelsachsen", "Mittweida", "Sachsen" },
    new String[]{ "MYK", "Landkreis Mayen-Koblenz in Koblenz", "Mayen-Koblenz", "Rheinland-Pfalz" },
    new String[]{ "MZ", "Stadt Mainz (XX 999 und AA–KY 9999)", "Mainz", "Rheinland-Pfalz" },
    new String[]{ "MZG", "Landkreis Merzig-Wadern in Merzig", "Merzig", "Saarland" },
    new String[]{ "N", "Stadt Nürnberg", "Nürnberg", "Bayern" },
    new String[]{ "NB", "Stadt Neubrandenburg (Große kreisangehörige Stadt im Landkreis Mecklenburgische Seenplatte)", "Neubrandenburg", "Mecklenburg-Vorpommern" },
    new String[]{ "ND", "Landkreis Neuburg-Schrobenhausen in Neuburg an der Donau", "Neuburg an der Donau", "Bayern" },
    new String[]{ "NDH", "Landkreis Nordhausen", "Nordhausen", "Thüringen" },
    new String[]{ "NE", "Rhein-Kreis Neuss in Neuss", "Neuss", "Nordrhein-Westfalen" },
    new String[]{ "NEA", "Landkreis Neustadt an der Aisch-Bad Windsheim in Neustadt an der Aisch", "Neustadt an der Aisch", "Bayern" },
    new String[]{ "NEB", "Burgenlandkreis", "Nebra", "Sachsen-Anhalt" },
    new String[]{ "NES", "Landkreis Rhön-Grabfeld in Bad Neustadt an der Saale", "Bad Neustadt an der Saale", "Bayern" },
    new String[]{ "NEW", "Landkreis Neustadt an der Waldnaab", "Neustadt an der Waldnaab", "Bayern" },
    new String[]{ "NF", "Kreis Nordfriesland in Husum", "Nordfriesland", "Schleswig-Holstein" },
    new String[]{ "NH", "Landkreis Sonneberg", "Neuhaus am Rennweg", "Thüringen" },
    new String[]{ "NI", "Landkreis Nienburg/Weser", "Nienburg/Weser", "Niedersachsen" },
    new String[]{ "NK", "Landkreis Neunkirchen in Ottweiler", "Neunkirchen", "Saarland" },
    new String[]{ "NL", "Niedersachsen", " Landesregierung und Landtag", "Niedersächsischer Landtag", "Niedersachsen" },
    new String[]{ "NM", "Landkreis Neumarkt in der Oberpfalz", "Neumarkt", "Bayern" },
    new String[]{ "NMB", "Burgenlandkreis", "Naumburg", "Sachsen-Anhalt" },
    new String[]{ "NMS", "Stadt Neumünster", "Neumünster", "Schleswig-Holstein" },
    new String[]{ "NOH", "Landkreis Grafschaft Bentheim in Nordhorn", "Nordhorn", "Niedersachsen" },
    new String[]{ "NOL", "Landkreis Görlitz", "Niederschlesischer Oberlausitzkreis", "Sachsen" },
    new String[]{ "NOM", "Landkreis Northeim", "Northeim", "Niedersachsen" },
    new String[]{ "NOR", "Landkreis Aurich", "Norden", "Niedersachsen" },
    new String[]{ "NP", "Landkreis Ostprignitz-Ruppin", "Neuruppin", "Brandenburg" },
    new String[]{ "NR", "Landkreis Neuwiedm", " Neuwied am Rhein", "Rheinland-Pfalz" },
    new String[]{ "NRÜ", "Hannover", "Neustadt am Rübenberge", "Niedersachsen" },
    new String[]{ "NRW", "Nordrhein-Westfalen", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Nordrhein-Westfalen", "Nordrhein-Westfalen" },
    new String[]{ "NU", "Landkreis Neu-Ulm", "Neu-Ulm", "Bayern" },
    new String[]{ "NVP", "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "Nordvorpommern", "Mecklenburg-Vorpommern" },
    new String[]{ "NW", "Stadt Neustadt an der Weinstraße", "Neustadt an der Weinstraße", "Rheinland-Pfalz" },
    new String[]{ "NWM", "Landkreis Nordwestmecklenburg in Wismar (ohne Stadt Wismar)", "Nordwestmecklenburg", "Mecklenburg-Vorpommern" },
    new String[]{ "NY", "Landkreis Görlitz", "Niesky", "Sachsen" },
    new String[]{ "NZ", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Neustrelitz", "Mecklenburg-Vorpommern" },
    new String[]{ "OA", "Landkreis Oberallgäu in Sonthofen", "Oberallgäu", "Bayern" },
    new String[]{ "OAL", "Landkreis Ostallgäu in Marktoberdorf", "Ostallgäu", "Bayern" },
    new String[]{ "OB", "Stadt Oberhausen", "Oberhausen", "Nordrhein-Westfalen" },
    new String[]{ "OBG", "Landkreis Stendal", "Osterburg", "Sachsen-Anhalt" },
    new String[]{ "OC", "Landkreis Börde", "Oschersleben", "Sachsen-Anhalt" },
    new String[]{ "OD", "Kreis Stormarn in Bad Oldesloe", "Bad Oldesloe", "Schleswig-Holstein" },
    new String[]{ "OE", "Kreis Olpe", "Olpe", "Nordrhein-Westfalen" },
    new String[]{ "OF", "Landkreis Offenbach in Dietzenbach (XX 999 und 9999)", "Offenbach", "Hessen" },
    new String[]{ "OG", "Ortenaukreis in Offenburg", "Offenburg", "Baden-Württemberg" },
    new String[]{ "OH", "Kreis Ostholstein in Eutin", "Ostholstein", "Schleswig-Holstein" },
    new String[]{ "OHA", "Landkreis Osterode am Harz", "Osterode am Harz", "Niedersachsen" },
    new String[]{ "OHV", "Landkreis Oberhavel in Oranienburg", "Oberhavel", "Brandenburg" },
    new String[]{ "OHZ", "Landkreis Osterholz in Osterholz-Scharmbeck", "Osterholz", "Niedersachsen" },
    new String[]{ "OK", "Landkreis Börde", "Ohrekreis", "Sachsen-Anhalt" },
    new String[]{ "OL", "Stadt Oldenburg (Oldenburg) (XX 999)", "Oldenburg", "Niedersachsen" },
    new String[]{ "OPR", "Landkreis Ostprignitz-Ruppin in Neuruppin", "Ostprignitz-Ruppin", "Brandenburg" },
    new String[]{ "OS", "Landkreis Osnabrück (XX 999)", "Osnabrück", "Niedersachsen" },
    new String[]{ "OSL", "Landkreis Oberspreewald-Lausitz in Senftenberg", "Oberspreewald-Lausitz", "Brandenburg" },
    new String[]{ "OVL", "Vogtlandkreis", "Obervogtland", "Sachsen" },
    new String[]{ "OZ", "Landkreis Nordsachsen", "Oschatz", "Sachsen" },
    new String[]{ "P", "Stadt Potsdam", "Potsdam", "Brandenburg" },
    new String[]{ "PA", "Landkreis Passau (XX 9", " 99 und 999)", "Passau", "Bayern" },
    new String[]{ "PAF", "Landkreis Pfaffenhofen an der Ilm", "Pfaffenhofen", "Bayern" },
    new String[]{ "PAN", "Landkreis Rottal-Inn in Pfarrkirchen", "Pfarrkirchen", "Bayern" },
    new String[]{ "PB", "Kreis Paderborn", "Paderborn", "Nordrhein-Westfalen" },
    new String[]{ "PCH", "Landkreis Parchim (jetzt Landkreis Ludwigslust-Parchim)", "Parchim", "Mecklenburg-Vorpommern" },
    new String[]{ "PE", "Landkreis Peine", "Peine", "Niedersachsen" },
    new String[]{ "PF", "Stadt Pforzheim (XX 999 und NA-ZZ 9999)", "Pforzheim", "Baden-Württemberg" },
    new String[]{ "PI", "Kreis Pinneberg", "Pinneberg", "Schleswig-Holstein" },
    new String[]{ "PIR", "Landkreis Sächsische Schweiz-Osterzgebirge in Pirna", "Pirna", "Sachsen" },
    new String[]{ "PL", "Vogtlandkreis", "Plauen", "Sachsen" },
    new String[]{ "PLÖ", "Kreis Plön", "Plön", "Schleswig-Holstein" },
    new String[]{ "PM", "Landkreis Potsdam-Mittelmark in Bad Belzig", "Potsdam-Mittelmark", "Brandenburg" },
    new String[]{ "PN", "Saale-Orla-Kreis", "Pößneck", "Thüringen" },
    new String[]{ "PR", "Landkreis Prignitz in Perleberg", "Prignitz", "Brandenburg" },
    new String[]{ "PRÜ", "Eifelkreis Bitburg-Prüm", "Prüm", "Rheinland-Pfalz" },
    new String[]{ "PS", "Landkreis Südwestpfalz in Pirmasens (XX 99 und 999)", "Pirmasens", "Rheinland-Pfalz" },
    new String[]{ "PW", "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "Pasewalk", "Mecklenburg-Vorpommern" },
    new String[]{ "QFT", "Saalekreis", "Querfurt", "Sachsen-Anhalt" },
    new String[]{ "QLB", "Landkreis Harz", "Quedlinburg", "Sachsen-Anhalt" },
    new String[]{ "R", "Stadt Regensburg (XX 999 und 9999)", "Regensburg", "Bayern" },
    new String[]{ "RA", "Landkreis Rastatt", "Rastatt", "Baden-Württemberg" },
    new String[]{ "RC", "Vogtlandkreis", "Reichenbach im Vogtland", "Sachsen" },
    new String[]{ "RD", "Kreis Rendsburg-Eckernförde in Rendsburg", "Rendsburg", "Schleswig-Holstein" },
    new String[]{ "RDG", "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "Ribnitz-Damgarten", "Mecklenburg-Vorpommern" },
    new String[]{ "RE", "Kreis Recklinghausen", "Recklinghausen", "Nordrhein-Westfalen" },
    new String[]{ "REG", "Landkreis Regen", "Regen", "Bayern" },
    new String[]{ "RG", "Landkreis Meißen", "Landkreis Riesa-Großenhain", "Sachsen" },
    new String[]{ "RH", "Landkreis Roth", "Roth", "Bayern" },
    new String[]{ "RI", "Landkreis Schaumburg", "Rinteln", "Niedersachsen" },
    new String[]{ "RIE", "Landkreis Meißen", "Riesa", "Sachsen" },
    new String[]{ "RL", "Landkreis Mittelsachsen", "Rochlitz", "Sachsen" },
    new String[]{ "RM", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Röbel/Müritz", "Mecklenburg-Vorpommern" },
    new String[]{ "RO", "Landkreis Rosenheim (XX 999; X 9999; XX 9999)", "Rosenheim", "Bayern" },
    new String[]{ "ROS", "Landkreis Rostock", "Rostock", "Mecklenburg-Vorpommern" },
    new String[]{ "ROW", "Landkreis Rotenburg (Wümme)", "Rotenburg an der Wümme", "Niedersachsen" },
    new String[]{ "RP", "Rhein-Pfalz-Kreis in Ludwigshafen am Rhein", "Rhein-Pfalz", "Rheinland-Pfalz" },
    new String[]{ "RPL", "Rheinland-Pfalz", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Rheinland-Pfälzischer Landtag", "Rheinland-Pfalz" },
    new String[]{ "RS", "Stadt Remscheid", "Remscheid", "Nordrhein-Westfalen" },
    new String[]{ "RSL", "Stadt Dessau-Roßlau", "Roßlau (Elbe)", "Sachsen-Anhalt" },
    new String[]{ "RT", "Landkreis Reutlingen", "Reutlingen", "Baden-Württemberg" },
    new String[]{ "RU", "Landkreis Saalfeld-Rudolstadt", "Rudolstadt", "Thüringen" },
    new String[]{ "RÜD", "Rheingau-Taunus-Kreis in Bad Schwalbach", "Rüdesheim", "Hessen" },
    new String[]{ "RÜG", "Landkreis Vorpommern-Rügen", "Rügen", "Mecklenburg-Vorpommern" },
    new String[]{ "RV", "Landkreis Ravensburg", "Ravensburg", "Baden-Württemberg" },
    new String[]{ "RW", "Landkreis Rottweil", "Rottweil", "Baden-Württemberg" },
    new String[]{ "RZ", "Kreis Herzogtum Lauenburg in Ratzeburg", "Ratzeburg", "Schleswig-Holstein" },
    new String[]{ "S", "Stadt Stuttgart", "Stuttgart", "Baden-Württemberg" },
    new String[]{ "SAB", "Landkreis Trier-Saarburg", "Saarburg", "Rheinland-Pfalz" },
    new String[]{ "SAD", "Landkreis Schwandorf", "Schwandorf", "Bayern" },
    new String[]{ "SAL", "Saarland", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Saarländischer Landtag", "Saarland" },
    new String[]{ "SAW", "Altmarkkreis Salzwedel in Salzwedel", "Salzwedel", "Sachsen-Anhalt" },
    new String[]{ "SB", "Regionalverband Saarbrücken (ohne die Stadt Völklingen)", "Saarbrücken", "Saarland" },
    new String[]{ "SBK", "Salzlandkreis", "Schönebeck (Elbe)", "Sachsen-Anhalt" },
    new String[]{ "SC", "Stadt Schwabach", "Schwabach", "Bayern" },
    new String[]{ "SCZ", "Saale-Orla-Kreis", "Schleiz", "Thüringen" },
    new String[]{ "SDH", "Kyffhäuserkreis", "Sondershausen", "Thüringen" },
    new String[]{ "SDL", "Landkreis Stendal", "Stendal", "Sachsen-Anhalt" },
    new String[]{ "SE", "Kreis Segeberg in Bad Segeberg", "Bad Segeberg", "Schleswig-Holstein" },
    new String[]{ "SEB", "Landkreis Sächsische Schweiz-Osterzgebirge", "Sebnitz", "Sachsen" },
    new String[]{ "SEE", "Landkreis Märkisch-Oderland", "Seelow", "Brandenburg" },
    new String[]{ "SFB", "Landkreis Oberspreewald-Lausitz", "Senftenberg", "Brandenburg" },
    new String[]{ "SFT", "Salzlandkreis", "Staßfurt", "Sachsen-Anhalt" },
    new String[]{ "SG", "Stadt Solingen", "Solingen", "Nordrhein-Westfalen" },
    new String[]{ "SGH", "Landkreis Mansfeld-Südharz", "Sangerhausen", "Sachsen-Anhalt" },
    new String[]{ "SH", "Schleswig-Holstein", " Landesregierung", " Landtag und Polizeinew String[]{2}", "Schleswig-Holstein", "Schleswig-Holstein" },
    new String[]{ "SHA", "Landkreis Schwäbisch Hall", "Schwäbisch Hall", "Baden-Württemberg" },
    new String[]{ "SHG", "Landkreis Schaumburg in Stadthagen", "Schaumburg oder Stadthagen", "Niedersachsen" },
    new String[]{ "SHK", "Saale-Holzland-Kreis in Eisenberg (Thüringen)", "Saale-Holzland-Kreis", "Thüringen" },
    new String[]{ "SHL", "Stadt Suhl", "Suhl", "Thüringen" },
    new String[]{ "SI", "Kreis Siegen-Wittgenstein in Siegen", "Siegen", "Nordrhein-Westfalen" },
    new String[]{ "SIG", "Landkreis Sigmaringen", "Sigmaringen", "Baden-Württemberg" },
    new String[]{ "SIM", "Rhein-Hunsrück-Kreis in Simmern/Hunsrück", "Simmern", "Rheinland-Pfalz" },
    new String[]{ "SK", "Saalekreis in Merseburg", "Saalekreis", "Sachsen-Anhalt" },
    new String[]{ "SL", "Kreis Schleswig-Flensburg in Schleswig", "Schleswig", "Schleswig-Holstein" },
    new String[]{ "SLE", "Kreis Euskirchen", "Schleiden", "Nordrhein-Westfalen" },
    new String[]{ "SLF", "Landkreis Saalfeld-Rudolstadt in Saalfeld/Saale", "Saalfeld", "Thüringen" },
    new String[]{ "SLK", "Salzlandkreis in Bernburg", "Salzlandkreis", "Sachsen-Anhalt" },
    new String[]{ "SLN", "Landkreis Altenburger Land", "Schmölln", "Thüringen" },
    new String[]{ "SLS", "Landkreis Saarlouis", "Saarlouis", "Saarland" },
    new String[]{ "SLÜ", "Main-Kinzig-Kreis (ohne die Stadt Hanau)", "Schlüchtern", "Hessen" },
    new String[]{ "SLZ", "Wartburgkreis", "Bad Salzungen", "Thüringen" },
    new String[]{ "SM", "Landkreis Schmalkalden-Meiningen in Meiningen", "Schmalkalden-Meiningen", "Thüringen" },
    new String[]{ "SN", "Stadt Schwerin", "Schwerin", "Mecklenburg-Vorpommern" },
    new String[]{ "SO", "Kreis Soest", "Soest", "Nordrhein-Westfalen" },
    new String[]{ "SOK", "Saale-Orla-Kreis in Schleiz", "Saale-Orla-Kreis", "Thüringen" },
    new String[]{ "SÖM", "Landkreis Sömmerda", "Sömmerda", "Thüringen" },
    new String[]{ "SON", "Landkreis Sonneberg", "Sonneberg", "Thüringen" },
    new String[]{ "SP", "Stadt Speyer", "Speyer", "Rheinland-Pfalz" },
    new String[]{ "SPB", "Landkreis Spree-Neiße", "Spremberg", "Brandenburg" },
    new String[]{ "SPN", "Landkreis Spree-Neiße in Forst (Lausitz)", "Spree-Neiße", "Brandenburg" },
    new String[]{ "SR", "Landkreis Straubing-Bogen in Straubing (XX 99 und 999)", "Straubing", "Bayern" },
    new String[]{ "SRB", "Landkreis Märkisch-Oderland", "Strausberg", "Brandenburg" },
    new String[]{ "SRO", "Saale-Holzland-Kreis", "Stadtroda", "Thüringen" },
    new String[]{ "ST", "Kreis Steinfurt", "Steinfurt", "Nordrhein-Westfalen" },
    new String[]{ "STA", "Landkreis Starnberg", "Starnberg", "Bayern" },
    new String[]{ "STD", "Landkreis Stade", "Stade", "Niedersachsen" },
    new String[]{ "STL", "Erzgebirgskreis", "Stollberg/Erzgeb.", "Sachsen" },
    new String[]{ "SU", "Rhein-Sieg-Kreis in Siegburg", "Siegburg", "Nordrhein-Westfalen" },
    new String[]{ "SÜW", "Landkreis Südliche Weinstraße in Landau in der Pfalz", "Südliche Weinstraße", "Rheinland-Pfalz" },
    new String[]{ "SW", "Landkreis Schweinfurt (XX 999 und XX 9999)", "Schweinfurt", "Bayern" },
    new String[]{ "SZ", "Stadt Salzgitter", "Salzgitter", "Niedersachsen" },
    new String[]{ "SZB", "Erzgebirgskreis", "Schwarzenberg/Erzgeb.", "Sachsen" },
    new String[]{ "TBB", "Main-Tauber-Kreis in Tauberbischofsheim", "Tauberbischofsheim", "Baden-Württemberg" },
    new String[]{ "TDO", "Landkreis Nordsachsen in Torgau", "Torgau", " Delitzsch", " Oschatz", "Sachsen" },
    new String[]{ "TET", "Landkreis Rostock", "Teterow", "Mecklenburg-Vorpommern" },
    new String[]{ "TF", "Landkreis Teltow-Fläming in Luckenwalde", "Teltow-Fläming", "Brandenburg" },
    new String[]{ "TG", "Landkreis Nordsachsen", "Torgau", "Sachsen" },
    new String[]{ "THL", "Thüringen", " Landesregierung und Landtag", "Thüringer Landtag", "Thüringen" },
    new String[]{ "THW", "Bundesanstalt Technisches Hilfswerk", "Technisches Hilfswerk", "bundesweit" },
    new String[]{ "TIR", "Landkreis Tirschenreuth", "Tirschenreuth", "Bayern" },
    new String[]{ "TO", "Landkreis Nordsachsen", "Landkreis Torgau-Oschatz", "Sachsen" },
    new String[]{ "TÖL", "Landkreis Bad Tölz-Wolfratshausen in Bad Tölz", "Bad Tölz", "Bayern" },
    new String[]{ "TR", "Landkreis Trier-Saarburg in Trier", "Trier", "Rheinland-Pfalz" },
    new String[]{ "TS", "Landkreis Traunstein", "Traunstein", "Bayern" },
    new String[]{ "TÜ", "Landkreis Tübingen", "Tübingen", "Baden-Württemberg" },
    new String[]{ "TUT", "Landkreis Tuttlingen", "Tuttlingen", "Baden-Württemberg" },
    new String[]{ "UE", "Landkreis Uelzen", "Uelzen", "Niedersachsen" },
    new String[]{ "UEM", "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "Ueckermünde", "Mecklenburg-Vorpommern" },
    new String[]{ "UH", "Unstrut-Hainich-Kreis in Mühlhausen/Thüringen", "Unstrut-Hainich", "Thüringen" },
    new String[]{ "UL", "Alb-Donau-Kreis in Ulm (XX 999 und NA-ZZ 9999)", "Ulm", "Baden-Württemberg" },
    new String[]{ "UM", "Landkreis Uckermark in Prenzlau", "Uckermark", "Brandenburg" },
    new String[]{ "UN", "Kreis Unna", "Unna", "Nordrhein-Westfalen" },
    new String[]{ "USI", "Hochtaunuskreis", "Usingen", "Hessen" },
    new String[]{ "V", "Vogtlandkreis in Plauen", "Vogtland", "Sachsen" },
    new String[]{ "VB", "Vogelsbergkreis in Lauterbach (Hessen)", "Vogelsberg", "Hessen" },
    new String[]{ "VEC", "Landkreis Vechta", "Vechta", "Niedersachsen" },
    new String[]{ "VER", "Landkreis Verden", "Verden", "Niedersachsen" },
    new String[]{ "VG", "Landkreis Vorpommern-Greifswald in Greifswald (ohne die Stadt Greifswald)", "Vorpommern", " Greifswald", "Mecklenburg-Vorpommern" },
    new String[]{ "VIE", "Kreis Viersen", "Viersen", "Nordrhein-Westfalen" },
    new String[]{ "VK", "Stadt Völklingen (Mittelstadt im Regionalverband Saarbrücken)", "Völklingen", "Saarland" },
    new String[]{ "VR", "Landkreis Vorpommern-Rügen in Stralsund (ohne die Stadt Stralsund)", "Vorpommern", " Rügen", "Mecklenburg-Vorpommern" },
    new String[]{ "VS", "Schwarzwald-Baar-Kreis in Villingen-Schwenningen", "Villingen-Schwenningen", "Baden-Württemberg" },
    new String[]{ "W", "Stadt Wuppertal", "Wuppertal", "Nordrhein-Westfalen" },
    new String[]{ "WAF", "Kreis Warendorf", "Warendorf", "Nordrhein-Westfalen" },
    new String[]{ "WAK", "Wartburgkreis in Bad Salzungen", "Wartburgkreis", "Thüringen" },
    new String[]{ "WAN", "Stadt Herne", "Wanne-Eickel", "Nordrhein-Westfalen" },
    new String[]{ "WAT", "Stadt Bochum", "Wattenscheid", "Nordrhein-Westfalen" },
    new String[]{ "WB", "Landkreis Wittenberg", "Wittenberg", "Sachsen-Anhalt" },
    new String[]{ "WBS", "Landkreis Eichsfeld", "Worbis", "Thüringen" },
    new String[]{ "WDA", "Landkreis Zwickau", "Werdau", "Sachsen" },
    new String[]{ "WE", "Stadt Weimar", "Weimar", "Thüringen" },
    new String[]{ "WEL", "Landkreis Limburg-Weilburg", "Weilburg", "Hessen" },
    new String[]{ "WEN", "Stadt Weiden in der Oberpfalz", "Weiden", "Bayern" },
    new String[]{ "WES", "Kreis Wesel", "Wesel", "Nordrhein-Westfalen" },
    new String[]{ "WF", "Landkreis Wolfenbüttel", "Wolfenbüttel", "Niedersachsen" },
    new String[]{ "WHV", "Stadt Wilhelmshaven", "Wilhelmshaven", "Niedersachsen" },
    new String[]{ "WI", "Stadt Wiesbaden", "Wiesbaden", "Hessen" },
    new String[]{ "WIL", "Landkreis Bernkastel-Wittlich in Wittlich", "Wittlich", "Rheinland-Pfalz" },
    new String[]{ "WIS", "Landkreis Nordwestmecklenburg", "Wismar", "Mecklenburg-Vorpommern" },
    new String[]{ "WIT", "Ennepe-Ruhr-Kreis", "Witten", "Nordrhein-Westfalen" },
    new String[]{ "WK", "Landkreis Ostprignitz-Ruppin", "Wittstock/Dosse", "Brandenburg" },
    new String[]{ "WL", "Landkreis Harburg in Winsen (Luhe)", "Winsen (Luhe)", "Niedersachsen" },
    new String[]{ "WLG", "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "Wolgast", "Mecklenburg-Vorpommern" },
    new String[]{ "WM", "Landkreis Weilheim-Schongau in Weilheim in Oberbayern", "Weilheim", "Bayern" },
    new String[]{ "WMS", "Landkreis Börde", "Wolmirstedt", "Sachsen-Anhalt" },
    new String[]{ "WN", "Rems-Murr-Kreis in Waiblingen", "Waiblingen", "Baden-Württemberg" },
    new String[]{ "WND", "Landkreis St. Wendel", "St. Wendel", "Saarland" },
    new String[]{ "WO", "Stadt Worms", "Worms", "Rheinland-Pfalz" },
    new String[]{ "WOB", "Stadt Wolfsburg", "Wolfsburg", "Niedersachsen" },
    new String[]{ "WOH", "Landkreis Kassel", "Wolfhagen", "Hessen" },
    new String[]{ "WR", "Landkreis Harz", "Wernigerode", "Sachsen-Anhalt" },
    new String[]{ "WRN", "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "Waren (Müritz)", "Mecklenburg-Vorpommern" },
    new String[]{ "WSF", "Burgenlandkreis", "Weißenfels", "Sachsen-Anhalt" },
    new String[]{ "WST", "Landkreis Ammerland in Westerstede", "Westerstede", "Niedersachsen" },
    new String[]{ "WSW", "Landkreis Görlitz", "Weißwasser", "Sachsen" },
    new String[]{ "WT", "Landkreis Waldshut in Waldshut-Tiengen", "Waldshut-Tiengen", "Baden-Württemberg" },
    new String[]{ "WTM", "Landkreis Wittmund", "Wittmund", "Niedersachsen" },
    new String[]{ "WÜ", "Stadt Würzburg (XX 999 und AA-NZ 9999)", "Würzburg", "Bayern" },
    new String[]{ "WUG", "Landkreis Weißenburg-Gunzenhausen in Weißenburg in Bayern", "Weißenburg", "Bayern" },
    new String[]{ "WUN", "Landkreis Wunsiedel im Fichtelgebirge", "Wunsiedel", "Bayern" },
    new String[]{ "WUR", "Landkreis Leipzig", "Wurzen", "Sachsen" },
    new String[]{ "WW", "Westerwaldkreis in Montabaur", "Westerwald", "Rheinland-Pfalz" },
    new String[]{ "WZ", "Stadt Wetzlar (Sonderstatusstadt im Lahn-Dill-Kreis)", "Wetzlar", "Hessen" },
    new String[]{ "WZL", "Landkreis Börde", "Wanzleben", "Sachsen-Anhalt" },
    new String[]{ "Z", "Landkreis Zwickau", "Zwickau", "Sachsen" },
    new String[]{ "ZE", "Landkreis Anhalt-Bitterfeld", "Zerbst/Anhalt", "Sachsen-Anhalt" },
    new String[]{ "ZEL", "Landkreis Cochem-Zell", "Zell (Mosel)", "Rheinland-Pfalz" },
    new String[]{ "ZI", "Landkreis Görlitz", "Zittau", "Sachsen" },
    new String[]{ "ZP", "Erzgebirgskreis", "Zschopau", "Sachsen" },
    new String[]{ "ZR", "Landkreis Greiz", "Zeulenroda", "Thüringen" },
    new String[]{ "ZW", "Stadt Zweibrücken", "Zweibrücken", "Rheinland-Pfalz" },
    new String[]{ "ZZ", "Burgenlandkreis", "Zeitz", "Sachsen-Anhalt" }
  };

  public final static String[][] AT = new String[][]{
    new String[]{ "AM", "Amstetten" },
    new String[]{ "B", "Bregenz" },
    new String[]{ "BA", "Bad Aussee" },
    new String[]{ "BB", "Österreichische Bundesbahnen" },
    new String[]{ "BG", "Bundesgendarmerie" },
    new String[]{ "BH", "Bundesheer" },
    new String[]{ "BK", "Konsul im Land Burgenland" },
    new String[]{ "BL", "Bruck an der Leitha" },
    new String[]{ "BM", "Bruck-Mürzzuschlag " },
    new String[]{ "BN", "Baden" },
    new String[]{ "BP", "Bundespolizei" },
    new String[]{ "BR", "Braunau am Inn" },
    new String[]{ "BZ", "Bludenz" },
    new String[]{ "DL", "Deutschlandsberg" },
    new String[]{ "DO", "Dornbirn" },
    new String[]{ "E", "Eisenstadt" },
    new String[]{ "EF", "Eferding" },
    new String[]{ "EU", "Eisenstadt-Umgebung" },
    new String[]{ "FB", "Feldbach" },
    new String[]{ "FE", "Feldkirchen" },
    new String[]{ "FF", "Fürstenfeld" },
    new String[]{ "FK", "Feldkirch" },
    new String[]{ "FR", "Freistadt" },
    new String[]{ "FV", "Finanzverwaltung" },
    new String[]{ "G", "Graz " },
    new String[]{ "GB", "Gröbming" },
    new String[]{ "GD", "Gmünd" },
    new String[]{ "GF", "Gänserndorf" },
    new String[]{ "GK", "Konsul in der Steiermark" },
    new String[]{ "GM", "Gmunden" },
    new String[]{ "GR", "Grieskirchen" },
    new String[]{ "GS", "Güssing" },
    new String[]{ "GU", "Graz-Umgebung" },
    new String[]{ "HA", "Hallein" },
    new String[]{ "HE", "Hermagor" },
    new String[]{ "HF", "Hartberg-Fürstenfeld" },
    new String[]{ "HL", "Hollabrunn" },
    new String[]{ "HO", "Horn" },
    new String[]{ "I", "Innsbruck " },
    new String[]{ "IL", "Innsbruck-Land" },
    new String[]{ "IM", "Imst" },
    new String[]{ "JE", "Jennersdorf" },
    new String[]{ "JO", "St. Johann im Pongau" },
    new String[]{ "JW", "Justizwache" },
    new String[]{ "K", "Klagenfurt am Wörthersee" },
    new String[]{ "KB", "Kitzbühel" },
    new String[]{ "KD", "Diplomatisches Korps in Kärnten" },
    new String[]{ "KI", "Kirchdorf an der Krems" },
    new String[]{ "KK", "Konsul im Land Kärnten" },
    new String[]{ "KL", "Klagenfurt-Land" },
    new String[]{ "KO", "Korneuburg" },
    new String[]{ "KR", "Krems-Land" },
    new String[]{ "KS", "Krems an der Donau " },
    new String[]{ "KU", "Kufstein" },
    new String[]{ "L", "Linz " },
    new String[]{ "LA", "Landeck" },
    new String[]{ "LB", "Leibnitz" },
    new String[]{ "LE", "Leoben " },
    new String[]{ "LF", "Lilienfeld" },
    new String[]{ "LI", "Liezen" },
    new String[]{ "LL", "Linz-Land" },
    new String[]{ "LN", "Leoben" },
    new String[]{ "LZ", "Lienz" },
    new String[]{ "MA", "Mattersburg" },
    new String[]{ "MD", "Mödling" },
    new String[]{ "ME", "Melk" },
    new String[]{ "MI", "Mistelbach" },
    new String[]{ "MT", "Murtal " },
    new String[]{ "MU", "Murau" },
    new String[]{ "MZ", "Mürzzuschlag" },
    new String[]{ "N", "Land Niederösterreich" },
    new String[]{ "ND", "Neusiedl am See" },
    new String[]{ "NK", "Neunkirchen" },
    new String[]{ "O", "Land Oberösterreich" },
    new String[]{ "OD", "Diplomatisches Korps in Oberösterreich" },
    new String[]{ "OK", "Konsul in Oberösterreich" },
    new String[]{ "OP", "Oberpullendorf" },
    new String[]{ "OW", "Oberwart" },
    new String[]{ "P", "St. Pölten" },
    new String[]{ "PE", "Perg" },
    new String[]{ "PL", "St. Pölten-Land" },
    new String[]{ "RA", "Radkersburg" },
    new String[]{ "RE", "Reutte" },
    new String[]{ "RI", "Ried im Innkreis" },
    new String[]{ "RO", "Rohrbach" },
    new String[]{ "S", "Salzburg " },
    new String[]{ "SB", "Scheibbs" },
    new String[]{ "SD", "Schärding" },
    new String[]{ "SE", "Steyr-Land" },
    new String[]{ "SK", "Konsul im Land Salzburg" },
    new String[]{ "SL", "Salzburg-Umgebung" },
    new String[]{ "SO", "Südoststeiermark " },
    new String[]{ "SP", "Spittal an der Drau" },
    new String[]{ "SR", "Steyr" },
    new String[]{ "ST", "Land Steiermark" },
    new String[]{ "SV", "St. Veit an der Glan" },
    new String[]{ "SW", "Schwechat" },
    new String[]{ "SZ", "Schwaz" },
    new String[]{ "T", "Land Tirol" },
    new String[]{ "TA", "Tamsweg" },
    new String[]{ "TD", "Diplomatisches Korps in Tirol" },
    new String[]{ "TK", "Konsul im Land Tirol" },
    new String[]{ "TU", "Tulln" },
    new String[]{ "UU", "Urfahr-Umgebung" },
    new String[]{ "V", "Land Vorarlberg" },
    new String[]{ "VB", "Vöcklabruck" },
    new String[]{ "VD", "Diplomatisches Korps in Vorarlberg" },
    new String[]{ "VI", "Villach " },
    new String[]{ "VK", "Völkermarkt" },
    new String[]{ "VL", "Villach-Land" },
    new String[]{ "VO", "Voitsberg" },
    new String[]{ "W", "Wien " },
    new String[]{ "WB", "Wiener Neustadt-Land" },
    new String[]{ "WD", "Diplomatisches Korps in Wien" },
    new String[]{ "WE", "Wels " },
    new String[]{ "WK", "Konsularkorps im Land Wien" },
    new String[]{ "WL", "Wels-Land" },
    new String[]{ "WN", "Wiener Neustadt" },
    new String[]{ "WO", "Wolfsberg" },
    new String[]{ "WT", "Waidhofen an der Thaya" },
    new String[]{ "WU", "Wien-Umgebung" },
    new String[]{ "WY", "Waidhofen an der Ybbs" },
    new String[]{ "WZ", "Weiz" },
    new String[]{ "ZE", "Zell am See" },
    new String[]{ "ZT", "Zwettl" }
  };

}
